#!/usr/bin/env bash
# Publish a build-artifact-only `release` branch.
#
# The `release` branch holds nothing but build output, so the plugin can be
# installed straight from GitHub with no local clone and no build step:
#
#   "plugin": ["github:recall704/opencode-remote-code#release"]
#
# Contents of the branch — a single, parentless (history-free) commit:
#
#   package.json   generated manifest (runtime deps only, no devDependencies,
#                  no scripts), so the branch doubles as an installable package
#   dist/          the compiled output of `npm run build`, including the
#                  self-contained drop-in bundle dist/plugins/remote-code.js
#
# No sources, no scripts, no launchers, no tsconfig, and no history from the
# source branch. The branch is regenerated from scratch on every publish, hence
# the force push.
#
# Usage:
#   bash scripts/publish-release.sh                  # build, commit, push
#   bash scripts/publish-release.sh --no-push        # build and commit only
#   RELEASE_REMOTE=origin bash scripts/publish-release.sh
#   RELEASE_SOURCE_BRANCH=dev bash scripts/publish-release.sh

set -euo pipefail

release_branch="${RELEASE_BRANCH:-release}"
source_branch="${RELEASE_SOURCE_BRANCH:-main}"
remote="${RELEASE_REMOTE:-recall704}"
remote_url="${RELEASE_REMOTE_URL:-https://github.com/recall704/opencode-remote-code.git}"

push=1
for arg in "$@"; do
  case "$arg" in
    --no-push) push=0 ;;
    -h | --help)
      sed -n '2,24p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "unknown option: $arg" >&2
      exit 2
      ;;
  esac
done

cd "$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"

if [ -n "$(git status --porcelain)" ]; then
  echo "[release] working tree is dirty — commit or stash first." >&2
  exit 1
fi

echo "[release] installing dependencies"
[ -d node_modules ] || npm install

echo "[release] building"
npm run build

# 1. Assemble the branch content: generated package.json + the build output.
staging="$(mktemp -d)"
trap 'rm -rf "$staging"' EXIT
pkg="$staging/pkg"
mkdir -p "$pkg"
cp -a dist "$pkg/dist"

source_sha="$(git rev-parse --short HEAD)"

RELEASE_SOURCE_SHA="$source_sha" \
  RELEASE_SOURCE_BRANCH="$source_branch" \
  RELEASE_REMOTE_URL="$remote_url" \
  node scripts/release-manifest.mjs package.json "$pkg/package.json"

echo "[release] branch content:"
( cd "$pkg" && find . -maxdepth 1 -mindepth 1 | sort | sed 's/^/  /' )
echo "  dist/ — $(find "$pkg/dist" -type f | wc -l) files, $(du -sh "$pkg/dist" | cut -f1)"

# 2. Turn it into a single parentless commit, without touching the working
#    tree: stage the artifact directory through a scratch index and let
#    commit-tree build the commit object (no parent = no source-branch history).
git_dir="$(git rev-parse --absolute-git-dir)"
index="$staging/index"
( cd "$pkg" && GIT_DIR="$git_dir" GIT_WORK_TREE="$pkg" GIT_INDEX_FILE="$index" git add -A . )
tree="$(GIT_INDEX_FILE="$index" git write-tree)"
commit="$(
  RELEASE_SOURCE_SHA="$source_sha" git commit-tree "$tree" -F - <<EOF
build(release): publish build artifacts

Generated by scripts/publish-release.sh from ${source_branch}@${source_sha}.

Contains the build output only — see the ${source_branch} branch for sources:
a generated package.json plus dist/ (including the drop-in bundle
dist/plugins/remote-code.js). No history is carried over; this branch is
recreated from scratch on every publish and force-pushed.

Install with: "plugin": ["github:recall704/opencode-remote-code#release"]
EOF
)"

git branch -f "$release_branch" "$commit"
echo "[release] $release_branch -> $(git rev-parse --short "$release_branch")"
git ls-tree -r --name-only "$release_branch" | awk -F/ '{print $1}' | sort | uniq -c | sed 's/^/  /'

# 3. Push.
if [ "$push" = "1" ]; then
  if ! git remote get-url "$remote" >/dev/null 2>&1; then
    echo "[release] adding remote '$remote' -> $remote_url"
    git remote add "$remote" "$remote_url"
  fi
  # The branch is regenerated on every publish, so a force push is expected.
  git push --force "$remote" "$release_branch"
  echo "[release] pushed $release_branch to $remote"
else
  echo "[release] --no-push: skipping push"
fi
